feat(connect):Support (min/max) constraints for DataGen connector
singularity-data/risingwave pull request #2737
Opened 2022-05-23 05:41 UTC by D2Lark

## What's changed and what's your intention?

As title

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)
- Add the 'user-facing changes' label if your PR contains changes that are visibile to users (optional) 

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
refer https://github.com/singularity-data/risingwave/issues/2401

2022-05-23 16:00 UTC, TennyZhuang commented on src/connector/src/datagen/mod.rs
> +    fields: HashMap<String, String>,
Better to add some comments here, e.g. Options related to fields

2022-05-23 16:02 UTC, TennyZhuang commented on src/connector/src/datagen/source/field_generator/mod.rs
> +pub trait FieldGenerator {
How about `NumericFieldGenerator`? I guess it cannot be applied to Timestamp/VARCHAR. And better to add some comments for pub trait.

2022-05-23 16:03 UTC, TennyZhuang commented on src/connector/src/datagen/source/field_generator/mod.rs
> +// Generator of this '#' field. Can be 'sequence' or 'random'.
```suggestion
/// Generator of this '#' field. Can be 'sequence' or 'random'.
```

2022-05-23 16:05 UTC, TennyZhuang commented on src/connector/src/datagen/source/field_generator/timestamp.rs
> +impl TimestampField {
```suggestion

impl TimestampField {
```

2022-05-24 07:15 UTC, shanicky requested changes

2022-05-24 07:15 UTC, shanicky commented on src/connector/src/datagen/source/field_generator/varchar.rs
> +use super::DEFAULT_LENGHT;
typo?

2022-05-24 07:17 UTC, D2Lark commented on src/connector/src/datagen/source/field_generator/varchar.rs
> +use super::DEFAULT_LENGHT;
I will fix that..

2022-05-25 09:23 UTC, TennyZhuang commented
rustdoc recommends `///` to write doc comments and `//` to write normal comments.

https://doc.rust-lang.org/rust-by-example/meta/doc.html

2022-05-26 05:47 UTC, TennyZhuang commented
Please resolve conflicts

2022-05-27 06:51 UTC, TennyZhuang approved these changes

2022-05-30 06:39 UTC, shanicky approved these changes
LGTM

2022-05-31 06:07 UTC, merged