feat(expr): add `vnode` internal function
singularity-data/risingwave pull request #4262
Opened 2022-07-28 10:00 UTC by richardchien

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Add `vnode` function.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

#4247

2022-07-28 10:48 UTC, fuyufjh commented
Need to refactor to variable vnode after #3396

2022-07-28 10:56 UTC, fuyufjh approved these changes
LGTM.

By the way, should we expose it as a function for debug purpose? cc. @st1page

2022-07-28 10:58 UTC, richardchien commented
> By the way, should we expose it as a function for debug purpose? cc. @st1page 

Exposing it as `_vnode` sounds good to me.

2022-07-28 11:02 UTC, BugenZhao requested changes

2022-07-28 11:02 UTC, BugenZhao commented on src/expr/src/expr/expr_vnode.rs
> +        }
I think we should avoid collecting owned rows here and reuse `StreamChunk::get_hash_values`, which is in a more columnar style. May check hash dispatcher for references.

https://github.com/singularity-data/risingwave/blob/5510952c00bc73922ec71b1dde06274fd6ad179a/src/stream/src/executor/dispatch.rs#L532-L537

2022-07-28 11:02 UTC, BugenZhao commented on src/expr/src/expr/expr_vnode.rs
> +        DataType::Int32
Int16 should be enough?
```suggestion
        DataType::Int16
```

2022-07-28 11:13 UTC, BugenZhao commented on src/expr/src/expr/expr_vnode.rs
> +            .collect::<Result<Vec<_>>>()?;
```suggestion
            .try_collect()?;
```

2022-07-28 11:13 UTC, BugenZhao commented on src/expr/src/expr/expr_vnode.rs
> +        let vnode = dist_key_row.hash_row(&CRC32FastBuilder {}).to_vnode() as i32;
May add a `FIXME` or note here: currently the implementation of the hash function in `Row::hash_row` differs from `Array::hash_at`, so their result might be different. #3457

2022-07-28 12:32 UTC, st1page commented on src/expr/src/expr/expr_vnode.rs
> +    dist_key_exprs: Vec<BoxedExpression>,
why not use `Vec<usize>`?

2022-07-29 03:09 UTC, st1page approved these changes
LGTM

2022-07-29 03:18 UTC, BugenZhao approved these changes
LGTM

2022-07-29 03:53 UTC, richardchien commented
@mergifyio requeue

2022-07-29 04:22 UTC, merged